# Generated by Django 2.2.1 on 2019-06-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(default='gen_default_code', max_length=50, verbose_name='code')),
                ('introduction', models.CharField(blank=True, default='', max_length=1000, verbose_name='introduction')),
                ('type', models.IntegerField(choices=[(0, '免费课'), (1, '普通课'), (2, 'VIP课')], default=0, verbose_name='type')),
            ],
        ),
    ]
