# Generated by Django 2.2.1 on 2019-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='<built-in function id>', max_length=50, verbose_name='code'),
        ),
    ]
