# Generated by Django 2.2.1 on 2019-06-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190623_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
