# Generated by Django 2.2.1 on 2019-06-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='000000', max_length=10, unique=True, verbose_name='code'),
        ),
    ]
