# Generated by Django 2.2.1 on 2019-06-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycard',
            name='valid_period',
            field=models.PositiveIntegerField(default=0, verbose_name='valid_period'),
        ),
    ]
