# Generated by Django 2.2.1 on 2019-06-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_smscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='mobile',
            field=models.CharField(error_messages={'unique': 'A user with that mobile number already exists.'}, max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
