# Generated by Django 2.2.1 on 2019-06-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190616_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='mobile',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with that mobile number already exists.'}, max_length=11, unique=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
