# Generated by Django 2.2.1 on 2019-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='mobile',
            field=models.CharField(db_index=True, error_messages={'unique': '该手机号已经存在'}, max_length=11, unique=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='type',
            field=models.IntegerField(choices=[(0, 'student'), (1, 'admin'), (2, 'school'), (3, 'agent')], default=0, verbose_name='user_type'),
        ),
    ]
