# Generated by Django 2.2.1 on 2019-06-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190616_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='是否使用过'),
        ),
    ]
