# Generated by Django 2.2.1 on 2019-06-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190619_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='name',
            field=models.CharField(default='学清用户', max_length=50, verbose_name='name'),
        ),
    ]
