# Generated by Django 2.2.1 on 2019-06-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190619_1650'),
        ('users', '0009_auto_20190619_1620'),
    ]

    operations = [
    ]
